// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: proto/service2.proto

package service2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioToTextService_ConvertAudioToText_FullMethodName = "/service2.AudioToTextService/ConvertAudioToText"
)

// AudioToTextServiceClient is the client API for AudioToTextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service2 converts audio to text.
type AudioToTextServiceClient interface {
	ConvertAudioToText(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, Transcription], error)
}

type audioToTextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioToTextServiceClient(cc grpc.ClientConnInterface) AudioToTextServiceClient {
	return &audioToTextServiceClient{cc}
}

func (c *audioToTextServiceClient) ConvertAudioToText(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, Transcription], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioToTextService_ServiceDesc.Streams[0], AudioToTextService_ConvertAudioToText_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, Transcription]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioToTextService_ConvertAudioToTextClient = grpc.BidiStreamingClient[AudioChunk, Transcription]

// AudioToTextServiceServer is the server API for AudioToTextService service.
// All implementations must embed UnimplementedAudioToTextServiceServer
// for forward compatibility.
//
// Service2 converts audio to text.
type AudioToTextServiceServer interface {
	ConvertAudioToText(grpc.BidiStreamingServer[AudioChunk, Transcription]) error
	mustEmbedUnimplementedAudioToTextServiceServer()
}

// UnimplementedAudioToTextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioToTextServiceServer struct{}

func (UnimplementedAudioToTextServiceServer) ConvertAudioToText(grpc.BidiStreamingServer[AudioChunk, Transcription]) error {
	return status.Errorf(codes.Unimplemented, "method ConvertAudioToText not implemented")
}
func (UnimplementedAudioToTextServiceServer) mustEmbedUnimplementedAudioToTextServiceServer() {}
func (UnimplementedAudioToTextServiceServer) testEmbeddedByValue()                            {}

// UnsafeAudioToTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioToTextServiceServer will
// result in compilation errors.
type UnsafeAudioToTextServiceServer interface {
	mustEmbedUnimplementedAudioToTextServiceServer()
}

func RegisterAudioToTextServiceServer(s grpc.ServiceRegistrar, srv AudioToTextServiceServer) {
	// If the following call pancis, it indicates UnimplementedAudioToTextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioToTextService_ServiceDesc, srv)
}

func _AudioToTextService_ConvertAudioToText_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioToTextServiceServer).ConvertAudioToText(&grpc.GenericServerStream[AudioChunk, Transcription]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioToTextService_ConvertAudioToTextServer = grpc.BidiStreamingServer[AudioChunk, Transcription]

// AudioToTextService_ServiceDesc is the grpc.ServiceDesc for AudioToTextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioToTextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service2.AudioToTextService",
	HandlerType: (*AudioToTextServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConvertAudioToText",
			Handler:       _AudioToTextService_ConvertAudioToText_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/service2.proto",
}
