// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: proto/headunit.proto

package headunit

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeadUnitService_StreamAudio_FullMethodName = "/headunit.HeadUnitService/StreamAudio"
)

// HeadUnitServiceClient is the client API for HeadUnitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HeadUnit service definition.
type HeadUnitServiceClient interface {
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, Transcription], error)
}

type headUnitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHeadUnitServiceClient(cc grpc.ClientConnInterface) HeadUnitServiceClient {
	return &headUnitServiceClient{cc}
}

func (c *headUnitServiceClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, Transcription], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HeadUnitService_ServiceDesc.Streams[0], HeadUnitService_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, Transcription]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HeadUnitService_StreamAudioClient = grpc.BidiStreamingClient[AudioChunk, Transcription]

// HeadUnitServiceServer is the server API for HeadUnitService service.
// All implementations must embed UnimplementedHeadUnitServiceServer
// for forward compatibility.
//
// HeadUnit service definition.
type HeadUnitServiceServer interface {
	StreamAudio(grpc.BidiStreamingServer[AudioChunk, Transcription]) error
	mustEmbedUnimplementedHeadUnitServiceServer()
}

// UnimplementedHeadUnitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeadUnitServiceServer struct{}

func (UnimplementedHeadUnitServiceServer) StreamAudio(grpc.BidiStreamingServer[AudioChunk, Transcription]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedHeadUnitServiceServer) mustEmbedUnimplementedHeadUnitServiceServer() {}
func (UnimplementedHeadUnitServiceServer) testEmbeddedByValue()                         {}

// UnsafeHeadUnitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeadUnitServiceServer will
// result in compilation errors.
type UnsafeHeadUnitServiceServer interface {
	mustEmbedUnimplementedHeadUnitServiceServer()
}

func RegisterHeadUnitServiceServer(s grpc.ServiceRegistrar, srv HeadUnitServiceServer) {
	// If the following call pancis, it indicates UnimplementedHeadUnitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeadUnitService_ServiceDesc, srv)
}

func _HeadUnitService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HeadUnitServiceServer).StreamAudio(&grpc.GenericServerStream[AudioChunk, Transcription]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HeadUnitService_StreamAudioServer = grpc.BidiStreamingServer[AudioChunk, Transcription]

// HeadUnitService_ServiceDesc is the grpc.ServiceDesc for HeadUnitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeadUnitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "headunit.HeadUnitService",
	HandlerType: (*HeadUnitServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _HeadUnitService_StreamAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/headunit.proto",
}
